name: Create DB User
on:
 workflow_dispatch:
   inputs:
     db_user:
       description: "Enter username to create"
       required: true
jobs:
 create-user:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v4
     - name: Install PostgreSQL client
       run: sudo apt-get update && sudo apt-get install -y postgresql-client
     - name: Create user in DB
       env:
         PGHOST: ${{ secrets.PGHOST }}
         PGPORT: ${{ secrets.PGPORT }}
         PGDATABASE: ${{ secrets.PGDATABASE }}
         PGUSER: ${{ secrets.PGUSER }}
         PGPASSWORD: ${{ secrets.PGPASSWORD }}
         NEW_DB_PASSWORD: ${{ secrets.NEW_DB_PASSWORD }}
         DB_USER: ${{ github.event.inputs.db_user }}
       run: |
         echo "Creating user: $DB_USER"
         psql -h $PGHOST -U $PGUSER -d $PGDATABASE <<EOF
         DO \$\$
         BEGIN
             IF NOT EXISTS (
                 SELECT FROM pg_roles WHERE rolname = '$DB_USER'
             ) THEN
                 CREATE USER "$DB_USER" WITH PASSWORD '$NEW_DB_PASSWORD';
                 RAISE NOTICE 'User created successfully';
             ELSE
                 RAISE NOTICE 'User already exists';
             END IF;
         END
         \$\$;
         EOF
     - name: Show all users
       env:
         PGHOST: ${{ secrets.PGHOST }}
         PGDATABASE: ${{ secrets.PGDATABASE }}
         PGUSER: ${{ secrets.PGUSER }}
         PGPASSWORD: ${{ secrets.PGPASSWORD }}
       run: |
         echo "Listing all users:"
         psql -h $PGHOST -U $PGUSER -d $PGDATABASE -c "\du"
